services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:80"
        networks:
            - bridge
        depends_on:
            - mysql
            - mailhog
    mysql:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: mysql
            MYSQL_DATABASE: db
            MYSQL_USER: mysql
            MYSQL_PASSWORD: mysql
        volumes:
            - mysql:/var/lib/mysql
        ports:
            - "3306:3306"
        restart: unless-stopped
        networks:
            - bridge
    mailhog:
        image: mailhog/mailhog
        ports:
            - "1025:1025"
            - "8025:8025"
        networks:
            - bridge
volumes:
    mysql: null
networks:
    bridge:
        driver: bridge
