services:
    mysql:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: mysql
            MYSQL_DATABASE: db
            MYSQL_USER: mysql
            MYSQL_PASSWORD: mysql
        volumes:
            - mysql:/var/lib/mysql
        ports:
            - "3306:3306"
        restart: unless-stopped
volumes:
    mysql: null
